site_name: "Sciml Bench"
site_url: ""
repo_url: https://github.com/stfc-sciml/sciml-bench/
docs_dir: markdown

plugins:
  - search
  - include_dir_to_nav

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - python
        - bash
nav:
    - Home: index.md
    - Main:
        - Introduction: main/introduction.md
        - Installation: main/installation.md
        - Usage: main/usage.md
        - Tutorial: main/tutorial.md
        - API: main/api.md
        - Contributing: main/contributing.md
        - FAQ: main/faq.md

    - Benchmarks: 
        - Summary of Benchmarks: benchmarks_summary.md
        - benchmarks

    - Datasets: 
        - Summary of Datasets: datasets_summary.md
        - datasets